
phototest:
  fetcher:
    recordCount: 120

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: false
        use_sql_comments: false

  datasource:
    name: Development Setup
    jdbc-url: jdbc:mysql://localhost:3306/phototest?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

server:
  port: 7080
  servlet:
    context-path: /phototest