
phototest:
  fetcher:
    recordCount: 120

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: false
        use_sql_comments: false

  datasource:
    name: Development Setup
    jdbc-url: jdbc:sqlite:docs/db/photoTest.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

server:
  port: 7080
  servlet:
    context-path: /phototest